#!/usr/bin/env bash
set -euo pipefail

# retro.sh - Generate retrospective summary document
# Usage: retro.sh "<summary>" [issue_url1] [issue_url2] ...

# ============================================
# Validate arguments
# ============================================
if [[ -z "${1:-}" ]]; then
  echo "Usage: retro.sh \"<summary>\" [issue_url1] [issue_url2] ..."
  echo ""
  echo "Example: retro.sh \"Sprint completed with 2 CAPS issues\" \"https://github.com/.../1\" \"https://github.com/.../2\""
  exit 1
fi

SUMMARY="$1"
shift
ISSUE_URLS=("${@:-}")

# ============================================
# Create retros directory
# ============================================
mkdir -p docs/retros

# ============================================
# Generate filename with timestamp
# ============================================
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H%M)
FILENAME="docs/retros/retro-${DATE}.md"

# If file already exists, add time suffix
if [[ -f "$FILENAME" ]]; then
  FILENAME="docs/retros/retro-${DATE}-${TIME}.md"
fi

# ============================================
# Get source repo for context
# ============================================
GIT_ORIGIN_URL=$(git config --get remote.origin.url 2>/dev/null || echo "unknown")
SOURCE_REPO=$(echo "$GIT_ORIGIN_URL" | sed -E 's#.*github\.com[:/]([^/]+/[^/.]+)(\.git)?$#\1#')

# ============================================
# Generate document
# ============================================
cat > "$FILENAME" << EOF
# Retrospective - ${DATE}

**Repository:** \`${SOURCE_REPO}\`
**Generated:** $(date -Iseconds)

## Summary

${SUMMARY}

## CAPS Improvements Proposed

EOF

# Add issue links if any
if [[ ${#ISSUE_URLS[@]} -gt 0 ]]; then
  for url in "${ISSUE_URLS[@]}"; do
    echo "- ${url}" >> "$FILENAME"
  done
else
  echo "_No upstream issues created this sprint._" >> "$FILENAME"
fi

# Add footer
cat >> "$FILENAME" << 'EOF'

----
*Generated by /retro command*
EOF

echo ""
echo "Retro saved to: $FILENAME"
